version: '3.8'

services:
  exp-assignment-1:
    image: ros:humble
    container_name: exp-assignment-2
    command: tail -f /dev/null
    ports:
      - 6080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}  
      - QT_X11_NO_MITSHM=1    
    volumes:
      - ./:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - /home/mehdi-khorasani/copy-of-dri-for-docker:/dev/dri
    extra_hosts:
    - "host.docker.internal:host-gateway"